// frontend/Player.svelte
<div class="flex">
  <audio 
    bind:this={audio}
		bind:paused
    on:play={stopOthers}
		on:playing={update}
		on:paused={update}
		on:timeupdate={update}
    src={src}
    preload="metadata"
  ></audio>
  <button class="btn" on:click={toggle}>
    <Icon icon={paused ? faPlay : faPause } />
  </button>
  <progress max="1" value={progress} />
</div>

<style>
.flex {
  grid-column-end: 3;
  grid-column-start: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.flex progress {
    flex-grow: 1;
    height: 8px;
    border: 1px solid var(--color);
}

progress[value]::-webkit-progress-bar {
  background-color: transparent;
}

progress[value]::-webkit-progress-value {
  background-color: var(--color);;
}
</style>

<script context="module">
	const elements = new Set();

	export function stopAll() {
		elements.forEach(element => {
			element.pause();
		});
	}
</script>

<script>
  import { onMount } from 'svelte';
  import Icon from 'fa-svelte';
  import { faPlay, faPause } from '@fortawesome/free-solid-svg-icons';

  export let src

	onMount(() => {
		elements.add(audio);
		return () => elements.delete(audio);
  });
  
  function stopOthers() {
		elements.forEach(element => {
			if (element !== audio) element.pause();
		});
  }
  
  function update() {
    progress = audio.currentTime / audio.duration;
  }

  function toggle() {
    paused ? audio.play() : audio.pause()
  }

  let audio;
  let paused = true;
  let progress = 0;
</script>

// old-src/components/Player.vue
<template>
  <div class="player">
    <audio @playing="update" @paused="update" @timeupdate="update" ref="player" :src="src" />
    <fa @click="toggle" class="icon" :icon="playing ? 'pause' : 'play'" />
    <progress :value="progress" max="1" />
  </div> 
</template>

<script>
export default {
  props: ['src'],
  data: () => ({
    playing: false,
    progress: 0,
  }),
  methods: {
    toggle() {
      if (this.playing) {
        this.pause()
      } else {
        this.play()
      }
    },
    play() {
      this.$refs.player.play()
      this.$emit('play')
    },
    pause() {
      this.$refs.player.pause()
      this.$emit('pause')
    },
    update() {
      let p = this.$refs.player;
      
      this.progress = p.currentTime / p.duration;
      this.playing = !this.$refs.player.paused
    }
  }
}
</script>

<style scoped>
.player {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}

.icon {
  margin-right: 5px;
}

progress {
  flex-grow: 1;
  color: var(--color);
  background: transparent;
  height: 8px;  
  -webkit-appearance: none;
  appearance: none;
  vertical-align: top;
  border-width: 1px;
  border-style: solid;
  border-color: currentcolor;
  overflow: hidden;
}

progress[value]::-webkit-progress-bar {
  background-color: transparent;
}

progress[value]::-webkit-progress-value {
  background-color: var(--color);;
}
</style>
