// frontend/RecentList.svelte

<div class="recent">
  <header class="header">
    <h1>Recently Played</h1>
    <LoadingIcon loading={$loadingRecent} />
  </header>
  {#if $recentTracks.length > 0}
    {#each $recentTracks as track}
    <SongCard track={track.track}/>
    {/each}
  {:else}
    {#each "|".repeat(19).split('|') as i}
    <div class="card" style="min-height: 12em;" />
    {/each}
  {/if}
</div>

<!-- {@debug $recentTracks} -->

<style>
  h1 {
    font-family: Quicksand;
  }

  .card {
    background: var(--card-bg);
  }
</style>

<script>
  import { recentTracks, loadingRecent } from './store'
  import LoadingIcon from './LoadingIcon.svelte'
  import SongCard from './SongCard.svelte'
</script>

// src/components/RecentList.vue
<template>
  <div class="recent">
    <header class="header">
      <h1>Recently Played</h1>
      <fa spin class="fader" :class="{show: loading.tracks}" icon="sync-alt" />
    </header>
    <template v-if="tracks.length > 0">
      <song-card :track="track" v-for="track in tracks" :key="track.track.id" />
    </template>
    <template v-else>
      <div class="card" v-for="i in 20" :key="i" style="min-height: 12em;">
      </div>
    </template>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import SongCard from './SongCard'
export default {
  computed: {
    ...mapGetters([
      'tracks',
      'loading'
    ]),
  },
  components: {
    SongCard,
  }
}
</script>
